// Data for 30 original IELTS Academic Writing Task 2 practice questions
// Structured as: id, type, promptText, modelAnswer

const IELTS_QUESTIONS_2 = [
    // Opinion (Agree/Disagree)
    { 
        id: "o1", 
        type: "opinion", 
        promptText: "Many people believe that university education should be free for everyone, regardless of their background. To what extent do you agree or disagree with this statement?",
        modelAnswer: "The question of whether tertiary education should be provided free of charge to all students is a matter of ongoing debate. While some argue that abolishing tuition fees would promote equality, I largely disagree with this notion, as doing so would place an unsustainable burden on the economy and potentially diminish the quality of education provided.\n\nFirst and foremost, funding universal free university education requires a massive allocation of state resources. Governments rely heavily on taxpayer money to fund public services. If they were to cover the tuition fees for every student, it would inevitably lead to significant tax increases or debilitating funding cuts to other essential sectors, such as healthcare, primary education, and infrastructure. For instance, in several Scandinavian countries where university is free, the overall tax rates are among the highest in the world, which may not be a viable or popular economic model for all nations.\n\nFurthermore, the quality of university education could suffer if institutions rely solely on government funding. Tuition fees inject crucial capital into universities, allowing them to attract top-tier professors, invest in cutting-edge research facilities, and maintain modern infrastructure. Without this independent revenue stream, universities might struggle to maintain high academic standards. A clear example of this can be seen in heavily subsidized educational systems in developing nations, where classrooms are frequently overcrowded and resources are severely lacking.\n\nHowever, I do acknowledge that higher education must remain accessible to academically gifted students from low-income backgrounds. Rather than making university free for everyone, a more pragmatic approach would be to expand scholarship programs, offer low-interest student loans, and implement means-tested grants. This ensures that talented individuals are not excluded due to financial constraints while ensuring the education system remains financially viable.\n\nIn conclusion, while the idea of free university education for all is idealistic and well-intentioned, it is economically impractical. Maintaining tuition fees, supplemented by robust financial aid for those in need, is a far more sustainable model that preserves educational standards."
    },
    { 
        id: "o2", 
        type: "opinion", 
        promptText: "The best way to reduce crime is to give longer prison sentences. To what extent do you agree or disagree?",
        modelAnswer: "The debate over how best to deter criminal activity often centers on the severity of punishment, with many advocating for extended prison sentences as the ultimate solution. While incarcerating offenders for longer periods does keep dangerous individuals off the streets, I strongly disagree that it is the 'best' or most effective way to reduce overall crime rates. Instead, addressing the root causes of crime and focusing on rehabilitation offer more sustainable solutions.\n\nFirstly, there is little empirical evidence to suggest that the threat of a lengthy prison sentence acts as an effective deterrent for most criminals. Many crimes are committed impulsively, under the influence of illicit substances, or out of desperate financial necessity. In these moments, the perpetrators rarely conduct a rational cost-benefit analysis regarding the length of potential jail time. For example, the United States imposes some of the longest prison sentences in the developed world, yet it continues to struggle with high rates of violent crime and recidivism compared to European nations with more lenient sentencing guidelines.\n\nFurthermore, focusing solely on punishment ignores the underlying socioeconomic drivers of crime. A significant proportion of criminal activity is rooted in poverty, lack of education, and unemployment. If governments merely lock offenders away without addressing these structural inequalities, crime will inevitably persist. A far more effective strategy involves investing in community programs, education, and job training in underprivileged areas, thereby removing the desperate circumstances that often drive individuals to break the law.\n\nFinally, the prison environment itself can often exacerbate criminal tendencies. Long sentences place non-violent offenders in close proximity to hardened criminals, transforming prisons into 'schools of crime'. Upon release, these individuals are heavily stigmatized and lack employable skills, making them highly likely to re-offend. A more progressive approach emphasizes rehabilitation, offering psychological counseling and vocational training within prisons to ensure inmates can successfully reintegrate into society.\n\nIn conclusion, while long prison sentences are necessary for the most dangerous individuals, they are a reactive and flawed approach to reducing overall crime. Proactive measures targeting socioeconomic inequality and rehabilitative programs represent far more effective strategies for creating a safer society."
    },
    { 
        id: "o3", 
        type: "opinion", 
        promptText: "Some people think that strict punishments for driving offences are the key to reducing traffic accidents. To what extent do you agree or disagree?",
        modelAnswer: "Traffic accidents represent a leading cause of injury and mortality globally, prompting governments to continuously seek effective preventative measures. While some argue that imposing severe penalties for driving offenses is the most crucial step in enhancing road safety, I partially agree with this view. Although strict punishments act as a vital deterrent, they must be combined with better infrastructure and improved driver education to comprehensively reduce accident rates.\n\nUndeniably, strict punishments play a fundamental role in enforcing traffic laws and deterring dangerous behavior. When drivers know that offenses such as speeding, running red lights, or driving under the influence carry heavy fines, license suspension, or even imprisonment, they are far more likely to adhere to the rules. A clear example of this is the dramatic reduction in drunk driving incidents following the introduction of severe penalties and mandatory breathalyzer tests in many Western countries. Fear of severe consequences forces motorists to drive more defensively, which inherently reduces the likelihood of collisions.\n\nHowever, relying solely on punitive measures is an incomplete strategy, as it fails to address accidents caused by human error or poor road conditions. Many accidents occur not out of reckless disregard for the law, but due to a lack of driving proficiency or sudden environmental hazards. Therefore, mandatory, high-quality driver education and rigorous testing are equally important. By ensuring that all motorists are fully competent and aware of defensive driving techniques before they even take to the roads, governments can prevent accidents from happening in the first place.\n\nFurthermore, infrastructure improvements are vital to road safety. Punishing a driver for crashing on a dangerous, poorly lit, or badly designed junction does not fix the underlying hazard. Governments must invest in intelligent traffic management systems, clearer signage, dedicated bicycle lanes, and better road maintenance to eliminate environmental risk factors.\n\nIn conclusion, while I agree that strict punishments are a necessary deterrent against reckless driving, they are not the sole key to reducing traffic accidents. A truly effective approach requires a multi-faceted strategy that pairs strict law enforcement with enhanced driver education and significant infrastructural improvements."
    },
    { id: "o4", type: "opinion", promptText: "In the future, nobody will buy printed newspapers or books because they will be able to read everything they want online without paying. To what extent do you agree or disagree with this statement?" },
    { id: "o5", type: "opinion", promptText: "It is often argued that the most important environmental problem of our time is the loss of particular species of plants and animals. To what extent do you agree or disagree?" },
    { id: "o6", type: "opinion", promptText: "Some people believe that parents should control the amount of time their children spend on social media. To what extent do you agree or disagree?" },

    // Discussion (Discuss both views and give your opinion)
    { 
        id: "d1", 
        type: "discussion", 
        promptText: "Some people think that technology has made our lives too complex and that the solution is to lead a simpler life without technology. Others, however, believe that technology is making our lives easier. Discuss both these views and give your own opinion.",
        modelAnswer: "In contemporary society, the rapid advancement of technology has profoundly impacted daily life. While some individuals argue that these innovations have needlessly complicated our existence and advocate for a return to a simpler, technology-free lifestyle, others contend that modern devices have significantly eased our burdens. This essay will examine both perspectives before concluding that technology's benefits far outweigh its complexities.\n\nThose who advocate for a simpler, less technologically dependent life often point to the stress and distraction caused by modern devices. The ubiquity of smartphones and the internet means that people are constantly connected, leading to an inability to switch off from work or social pressures. This constant connectivity can result in mental fatigue and a loss of meaningful, face-to-face interactions. Furthermore, the rapid pace of technological change requires individuals to constantly learn new systems and interfaces, which can be overwhelming, particularly for older generations. Consequently, retreating to a lifestyle free from such digital intrusions is seen as a way to reclaim peace of mind and foster deeper human connections.\n\nConversely, the opposing view emphasizes the unparalleled convenience and efficiency that technology introduces into our lives. From a practical standpoint, household appliances like washing machines and dishwashers have drastically reduced the time spent on domestic chores. In the professional sphere, computers and the internet have revolutionized communication and information retrieval, allowing for global collaboration and instantaneous access to vast repositories of knowledge. Medical technology, too, has advanced leaps and bounds, simplifying the diagnosis and treatment of diseases, thereby extending life expectancy and improving life quality.\n\nIn my opinion, while it is true that technology can introduce new layers of complexity and stress if not managed properly, abandoning it entirely is an extreme and regressive solution. The conveniences and advancements brought about by technological progress are simply too valuable to discard. Instead of rejecting technology, individuals should focus on establishing healthy boundaries and utilizing digital tools intentionally.\n\nIn conclusion, although the continuous evolution of technology can create challenges and a sense of complexity, its contributions to easing domestic burdens, enhancing global communication, and advancing medical science are undeniable. A balanced approach to technology usage is far more practical than striving for an entirely simplified, tech-free life."
    },
    { 
        id: "d2", 
        type: "discussion", 
        promptText: "Some people believe that unpaid community service should be a compulsory part of high school programmes. Others believe that it should be voluntary. Discuss both views and give your own opinion.",
        modelAnswer: "The integration of community service into high school curricula is a topic of considerable debate. While some educators and parents advocate for making unpaid community work a mandatory requirement for graduation, others argue that volunteering should remain a personal choice. This essay will examine both viewpoints before concluding that voluntary participation yields more genuine and long-lasting benefits.\n\nProponents of compulsory community service argue that it instills a sense of civic duty and social responsibility in young people. By forcing teenagers to engage with local charities, homeless shelters, or environmental clean-up initiatives, schools guarantee that all students gain exposure to societal issues outside their immediate social circles. This mandatory exposure can foster empathy, broaden their perspectives, and break down socioeconomic barriers. Furthermore, compulsory service ensures that every student acquires valuable practical skills and work experience, which can be highly beneficial when applying for universities or entering the job market.\n\nOn the other hand, those who believe community service should be voluntary argue that coercion defeats the very purpose of charity. If students are forced to volunteer simply to earn a grade or secure a diploma, they are likely to view the work as a tedious chore rather than a meaningful contribution. This resentment can lead to poor performance and a negative attitude towards the organizations they are supposedly helping. Moreover, teenagers already face immense academic pressure and demanding extracurricular schedules; adding a compulsory work requirement could lead to exhaustion and severe stress.\n\nIn my opinion, while the goal of fostering civic responsibility is noble, community service must remain voluntary to be truly effective. True altruism cannot be legislated or graded. Schools should heavily encourage and facilitate volunteer opportunities—perhaps by offering academic credits or awards as incentives—but they should stop short of making it a strict requirement. When students choose to volunteer independently, they are more engaged, passionate, and likely to continue their charitable efforts into adulthood.\n\nIn conclusion, although compulsory community service guarantees participation and provides broad exposure to societal issues, it risks breeding resentment and defeating the spirit of volunteerism. A system that actively encourages and rewards voluntary service is far more likely to develop genuinely compassionate and civic-minded individuals."
    },
    { 
        id: "d3", 
        type: "discussion", 
        promptText: "Some people think that zoos are cruel and should be closed down. Others, however, believe that zoos can be useful for protecting wild animals. Discuss both views and give your own opinion.",
        modelAnswer: "The existence of zoos has long been a subject of controversy. While animal rights activists argue that confining wild creatures is inherently cruel and advocate for their total closure, conservationists maintain that modern zoos play a vital role in protecting endangered species. This essay will consider both perspectives before concluding that, under strict ethical guidelines, zoos serve a necessary and beneficial purpose.\n\nThose who campaign against zoos primarily focus on the ethical implications of captivity. They argue that restricting animals, especially large predators and migratory species, to artificial enclosures denies them their natural behaviors and instincts. This confinement can lead to severe psychological distress, often manifested in repetitive pacing or self-harm, a condition known as 'zoochosis'. Furthermore, critics point out that despite claims of education, many zoos still prioritize entertainment and profit, treating animals as mere exhibits for public amusement rather than sentient beings deserving of a natural life in the wild.\n\nConversely, supporters of zoos highlight their indispensable role in modern wildlife conservation. As natural habitats are rapidly destroyed by deforestation and climate change, zoos often act as a last refuge for critically endangered species. Through international breeding programs, zoos have successfully rescued several species from the brink of extinction, such as the Californian Condor and the Arabian Oryx. Additionally, reputable zoos generate crucial funding for global conservation efforts and provide unparalleled educational opportunities. By allowing urban populations to see wild animals up close, zoos foster a sense of connection and empathy that inspires public support for environmental protection.\n\nIn my opinion, while the historical model of the 'caged menagerie' is undeniably cruel and outdated, modern conservation-focused zoos are essential. The unfortunate reality is that the wild is no longer safe for many species due to rampant human expansion. Therefore, well-regulated zoos with expansive, naturalistic enclosures provide a necessary sanctuary. The focus, however, must remain strictly on conservation and rehabilitation rather than commercial entertainment.\n\nIn conclusion, although the captivity of animals raises valid ethical concerns regarding animal welfare, the role of modern zoos in preventing extinction and funding conservation is too significant to ignore. Rather than closing them down, society should demand stricter ethical standards to ensure animal wellbeing remains the absolute priority."
    },
    { id: "d4", type: "discussion", promptText: "Some people think that competitive sports have a positive effect on the child's education, while others argue it is not so. Discuss both views and give your opinion." },
    { id: "d5", type: "discussion", promptText: "Some people say that advertising encourages us to buy things we really do not need. Others say that advertisements tell us about new products that may improve our lives. Discuss both views and give your opinion." },
    { id: "d6", type: "discussion", promptText: "Some people believe that university students should pay the full cost of their education, while others believe that higher education should be free. Discuss both views and give your opinion." },

    // Problem/Solution
    { 
        id: "ps1", 
        type: "problem_solution", 
        promptText: "Traffic congestion is becoming a major problem in many cities around the world. What are the main causes of this problem? How can it be solved?",
        modelAnswer: "In recent years, traffic congestion has escalated into a severe issue in numerous metropolitan areas globally. This essay will outline the primary causes behind this escalating problem before proposing viable solutions to mitigate it.\n\nThe most significant driver of urban traffic congestion is the sheer increase in private vehicle ownership. As economies grow and living standards improve, more individuals can afford cars, leading to a surplus of vehicles on infrastructure originally designed for a fraction of that volume. Furthermore, the inadequacy of public transportation systems in many cities exacerbates the issue. When trains and buses are unreliable, overcrowded, or expensive, commuters naturally gravitate towards the comfort and predictability of their own vehicles. Finally, the centralization of businesses and schools in downtown areas forces a massive influx of daily commuters to travel along the same routes during peak rush hours, inevitably creating gridlock.\n\nTo tackle this multifaceted issue, governments must implement a combination of infrastructural and policy-based solutions. Firstly, substantial investment must be directed towards expanding and subsidizing public transport networks. If public transit is made affordable, punctual, and comprehensive, a significant portion of the population will willingly abandon their cars. Secondly, city authorities could introduce congestion pricing, similar to the system used in London, where drivers are charged a fee for entering busy city centers during peak times. This acts as a strong financial deterrent against unnecessary driving. Lastly, encouraging decentralized work models, such as telecommuting and flexible working hours, would drastically reduce the volume of traffic during traditional rush hours.\n\nIn conclusion, while the surge in private car ownership and inadequate public transit systems have severely congested modern cities, the situation is not irreversible. By heavily investing in public transportation, implementing congestion charges, and promoting flexible working arrangements, authorities can effectively alleviate traffic jams and improve the quality of urban life."
    },
    { 
        id: "ps2", 
        type: "problem_solution", 
        promptText: "In many countries, an increasing number of people are suffering from health problems as a result of eating too much fast food. What are the causes of this problem? What solutions can you suggest?",
        modelAnswer: "The global proliferation of fast food has led to a parallel rise in diet-related health issues, such as obesity, diabetes, and heart disease, in many nations. This essay will examine the primary causes driving the overconsumption of fast food and propose effective strategies to combat this growing public health crisis.\n\nThe root cause of the modern reliance on fast food is the increasingly fast-paced nature of contemporary life. In dual-income households where both parents work long hours, there is significantly less time and energy available for preparing fresh, nutritious meals at home. Fast food offers unparalleled convenience, providing instant gratification for exhausted individuals. Secondly, aggressive and highly targeted marketing campaigns by fast-food conglomerates play a massive role, particularly those aimed at children. By offering toys and utilizing colorful mascots, these companies create lifelong dietary habits from a very young age. Finally, cost is a major factor; in many countries, heavily processed fast food is significantly cheaper than fresh fruits, vegetables, and lean proteins, forcing low-income families to rely on unhealthy diets out of economic necessity.\n\nAddressing this issue requires a coordinated effort from both governments and educational institutions. Firstly, authorities should introduce a 'sugar tax' or a 'junk food tax' to artificially inflate the price of unhealthy products. The revenue generated from this tax could then be used to subsidize the cost of fresh produce, making healthy eating financially accessible to everyone. Secondly, governments must implement strict regulations on advertising, particularly banning the advertisement of junk food during children's television programming to break the cycle of early addiction. Furthermore, schools need to take an active role by incorporating mandatory cooking and nutrition classes into the curriculum, ensuring the next generation possesses the knowledge and skills to prepare healthy meals.\n\nIn conclusion, the epidemic of fast-food-related health problems is driven by modern time constraints, aggressive marketing, and the cheap cost of processed food. However, by utilizing taxation to adjust food prices, regulating advertising, and prioritizing nutritional education, societies can effectively reverse this damaging trend."
    },
    { 
        id: "ps3", 
        type: "problem_solution", 
        promptText: "Many young people who leave school are unable to find jobs. What problems does this cause for individuals and for society? What measures can be taken to solve them?",
        modelAnswer: "Youth unemployment is an increasingly pressing issue in many countries worldwide, with a growing number of school leavers struggling to secure employment. This essay will discuss the detrimental effects this phenomenon has on both the individuals involved and society as a whole, before suggesting practical measures to alleviate the problem.\n\nThe consequences of youth unemployment are severe and multifaceted. On an individual level, failing to find work after years of schooling leads to profound frustration, a loss of self-esteem, and financial dependence on parents. This lack of financial independence delays young people from reaching major life milestones, such as leaving the family home or starting a family. From a societal perspective, a high rate of youth unemployment represents a massive waste of human capital and economic potential. Furthermore, a demographic of disenfranchised, idle youth is strongly correlated with increased rates of crime, vandalism, and social unrest, as marginalized individuals may turn to illegal activities out of desperation or boredom.\n\nTo effectively tackle this issue, governments and educational institutions must collaborate to bridge the gap between schooling and the job market. The most crucial measure is to reform the education system to prioritize practical, vocational training alongside traditional academic subjects. Schools should partner with local industries to offer apprenticeships and mandatory work placement programs, ensuring that students graduate with employable, real-world skills. Secondly, governments should offer financial incentives, such as tax breaks or wage subsidies, to companies that actively hire and train recent school leavers. This reduces the financial risk for employers taking on inexperienced staff. Finally, investing in entrepreneurial programs that provide funding and mentorship to young people wishing to start their own businesses can create new avenues for youth employment.\n\nIn conclusion, the inability of school leavers to find work causes significant psychological and financial distress for individuals while stunting economic growth and threatening social stability. However, by aligning educational curricula with industry needs and providing financial incentives for hiring young people, this crisis can be effectively managed."
    },
    { id: "ps4", type: "problem_solution", promptText: "In some countries, the average weight of people is increasing, and their levels of health and fitness are decreasing. What do you think are the causes of these problems and what measures could be taken to solve them?" },
    { id: "ps5", type: "problem_solution", promptText: "Nowadays, many families move to different countries for work. What problems does this cause for the children in the family? How might these problems be solved?" },
    { id: "ps6", type: "problem_solution", promptText: "The gap between the rich and the poor is growing wider in many parts of the world. What problems can this situation cause? What can be done to reduce this gap?" },

    // Advantages/Disadvantages
    { 
        id: "a1", 
        type: "adv_dis", 
        promptText: "More and more people are choosing to shop online rather than going to local shops. Do you think this is a positive or negative development?",
        modelAnswer: "The shift towards e-commerce has fundamentally altered consumer habits, with an increasing number of individuals preferring to purchase goods online rather than visiting traditional brick-and-mortar stores. While this trend has led to the decline of some local businesses, I believe it is overwhelmingly a positive development due to the unparalleled convenience and broader choices it offers consumers.\n\nAdmittedly, the rise of online shopping carries some negative consequences, primarily for local economies. Traditional high streets are suffering as small, independent retailers struggle to compete with the aggressive pricing and vast inventories of digital retail giants like Amazon. This can lead to vacant storefronts and job losses within the local community. Furthermore, the environmental impact of packaging waste and the carbon footprint associated with delivering individual parcels to millions of homes cannot be ignored.\n\nHowever, these drawbacks are eclipsed by the profound benefits e-commerce provides to the modern consumer. The primary advantage is convenience. Online shopping allows individuals to browse and purchase items at any time of day or night, eliminating the need to travel, find parking, or navigate crowded stores. This is particularly advantageous for those with demanding work schedules or reduced mobility. \n\nIn addition to convenience, the internet offers a truly global marketplace. Consumers are no longer restricted to the limited stock available in their immediate geographic vicinity. They can easily compare prices across multiple platforms, read detailed customer reviews, and access niche products from international sellers that would be impossible to find locally. This intense competition also drives down prices, ultimately saving the consumer money.\n\nIn conclusion, while the transition to online shopping presents genuine challenges for local retail sectors, the sheer convenience, cost-effectiveness, and infinite variety it provides to consumers make it a decidedly positive development in the modern era."
    },
    { 
        id: "a2", 
        type: "adv_dis", 
        promptText: "Nowadays many people choose to be self-employed, rather than to work for a company or organisation. Why might this be the case? Do the disadvantages of being self-employed outweigh the advantages?",
        modelAnswer: "In recent years, there has been a significant surge in the number of professionals opting for self-employment over traditional corporate careers. This essay will explore the reasons behind this shift in working patterns and argue that the advantages of being one's own boss generally outweigh the inherent disadvantages.\n\nThe primary motivation driving individuals towards self-employment is the pursuit of autonomy and flexibility. Unlike traditional employees who are bound by strict corporate schedules and rigid hierarchies, freelancers and entrepreneurs have the freedom to dictate their own working hours and choose the projects they find most fulfilling. This flexibility is particularly appealing to those seeking a better work-life balance, such as parents wishing to spend more time with their children. Furthermore, self-employment often offers a direct correlation between effort and income. Rather than receiving a fixed salary while generating wealth for an employer, self-employed individuals retain the full financial rewards of their hard work, providing a powerful incentive for ambition and innovation.\n\nHowever, self-employment is not without its drawbacks, the most prominent being financial instability. Freelancers lack the safety net of a guaranteed monthly paycheck, paid sick leave, and employer-sponsored health insurance. Income can fluctuate wildly from month to month, which can cause significant stress, particularly during economic downturns. Additionally, running an independent business requires handling administrative tasks, such as accounting, marketing, and taxes, which can be time-consuming and detract from the core work.\n\nDespite these challenges, I believe the benefits of self-employment outweigh the negatives. The modern digital economy, with its abundance of freelance platforms and global connectivity, has made it easier than ever to secure clients and maintain a steady stream of income. While financial uncertainty exists, the profound personal satisfaction derived from building one's own enterprise, coupled with the ultimate freedom to control one's daily life, makes it a highly rewarding career path for driven individuals.\n\nIn conclusion, the desire for autonomy and flexible working conditions are the main reasons people choose self-employment. While it entails financial risks and administrative burdens, the unparalleled freedom and potential for direct financial reward make it an advantageous and fulfilling choice."
    },
    { 
        id: "a3", 
        type: "adv_dis", 
        promptText: "In some countries, young people are encouraged to work or travel for a year between finishing high school and starting university studies. Discuss the advantages and disadvantages for young people who decide to do this.",
        modelAnswer: "The concept of a 'gap year'—taking a year off between high school and university to work or travel—has become increasingly popular among young adults in many Western nations. While this break from formal education can present certain challenges, I believe the personal growth and practical experience it offers make it an overwhelmingly advantageous pursuit.\n\nThere are several notable advantages to taking a gap year. Chief among them is the opportunity for immense personal development and broadening of horizons. Traveling internationally forces young people out of their comfort zones, teaching them independence, cultural empathy, and adaptability. These soft skills are invaluable and often difficult to acquire in a traditional classroom setting. Furthermore, choosing to work during this year provides crucial real-world experience. It allows school leavers to save money for their upcoming tuition fees while gaining practical skills and testing out potential career paths before committing to a specific, and expensive, university degree. This time spent reflecting often leads to a more focused and mature approach to their tertiary studies upon their return.\n\nConversely, there are undeniable disadvantages to delaying university. The most significant risk is a loss of academic momentum. After spending a year away from rigorous study and structured learning, some students find it incredibly difficult to re-adapt to the demands of academic writing and intensive studying. In extreme cases, the distraction of earning money or the allure of travel may cause individuals to abandon their plans for higher education entirely. Additionally, funding a year of travel can be prohibitively expensive, meaning this opportunity is often restricted to those from affluent backgrounds, thereby widening existing social inequalities.\n\nIn conclusion, while a gap year carries the risk of disrupting academic momentum and can be financially demanding, the advantages are far more substantial. The independence gained through travel and the practical skills acquired through employment equip young adults with a level of maturity and focus that ultimately enhances their subsequent university experience and future career prospects."
    },
    { id: "a4", type: "adv_dis", promptText: "Many cities are now actively encouraging people to use bicycles instead of cars. Do the advantages of this trend outweigh the disadvantages?" },
    { id: "a5", type: "adv_dis", promptText: "In many countries, children are engaged in some kind of paid work. Some people regard this as completely wrong, while others consider it as valuable work experience, important for learning and taking responsibility. What are the advantages and disadvantages of children doing paid work?" },
    { id: "a6", type: "adv_dis", promptText: "Some companies allow their employees to work from home instead of going to the office every day. Do the advantages of this outweigh the disadvantages?" },

    // Double Question
    { 
        id: "dq1", 
        type: "double", 
        promptText: "Today, more and more people are delaying having children until they are older. What are the reasons for this trend? Do you think this is a positive or negative development?",
        modelAnswer: "In recent decades, there has been a noticeable demographic shift, with an increasing number of individuals and couples opting to start families later in life. This essay will explore the socioeconomic reasons driving this trend and argue that, despite some biological risks, it is largely a positive development for both families and society.\n\nThe primary driver behind the delay in parenthood is the changing nature of modern career and educational trajectories. Today, both men and women are pursuing higher education and striving to establish secure careers before taking on the immense financial and temporal responsibilities of raising a child. In many contemporary economies, achieving financial stability requires years of dedication, making early parenthood economically daunting. Furthermore, the rising cost of living, particularly housing and childcare, forces many prospective parents to wait until they have accumulated sufficient savings. Another contributing factor is the shift in societal norms; there is less pressure to conform to traditional timelines, allowing individuals to prioritize personal growth and travel in their twenties.\n\nIn my view, this trend towards older parenthood is primarily positive. When individuals wait until they are older to have children, they are generally more financially secure, which allows them to provide a more stable and enriching environment for their offspring. They are less likely to struggle with the costs of education, healthcare, and extracurricular activities. Additionally, older parents often possess a higher degree of emotional maturity and life experience. Having had the time to fulfill personal ambitions, they may experience less resentment and be more patient and dedicated to the child-rearing process.\n\nWhile it is true that advanced maternal and paternal age can pose certain medical risks, modern advancements in healthcare and prenatal screening have significantly mitigated these dangers.\n\nIn conclusion, the decision to delay parenthood is a logical response to the financial and educational demands of the modern world. Because it generally results in children being raised in more secure, financially stable, and emotionally mature households, I consider it a highly positive societal development."
    },
    { 
        id: "dq2", 
        type: "double", 
        promptText: "Many people prefer to use public transport rather than driving their own cars. Why do you think this is? How can governments encourage more people to use public transport?",
        modelAnswer: "In many modern cities, there is a growing preference among commuters to utilize public transportation networks instead of relying on private vehicles. This essay will explore the reasons behind this shift in consumer behavior and suggest practical measures governments can take to further incentivize the use of mass transit.\n\nThe primary reason individuals are turning towards public transport is the escalating inconvenience and cost associated with driving in urban environments. As cities become increasingly congested, driving to work often involves enduring stressful, unpredictable traffic jams and wasting hours in gridlock. In contrast, dedicated bus lanes and underground rail networks bypass this surface congestion, offering a faster and more reliable commute. Furthermore, the financial burden of owning a car—encompassing fuel, insurance, maintenance, and exorbitant city parking fees—makes public transport a far more economical choice for the average citizen. Finally, there is a growing environmental consciousness among the public; many people choose buses and trains specifically to reduce their personal carbon footprint and contribute to cleaner city air.\n\nTo accelerate this positive trend and encourage even more people to abandon their cars, governments must focus on improving the quality and accessibility of public transit. The most effective strategy is to heavily subsidize ticket prices, making buses and trains unequivocally the cheapest way to travel. Secondly, governments must invest heavily in expanding route networks and increasing service frequency, ensuring that public transport is a viable option for those living in suburban and peripheral areas, not just city centers. Lastly, authorities should implement policies that actively discourage driving, such as introducing stringent congestion charges, reducing inner-city parking spaces, and pedestrianizing major shopping districts.\n\nIn conclusion, the preference for public transport is largely driven by a desire to avoid traffic congestion, save money, and protect the environment. By reducing ticket prices, expanding services, and making driving less convenient, governments can successfully encourage the widespread adoption of mass transit systems."
    },
    { 
        id: "dq3", 
        type: "double", 
        promptText: "In the modern world, it is possible to shop, work and communicate with people via the internet and live without any face-to-face contact with others. Is it a positive or negative development? What are the effects of this trend on individuals and society?",
        modelAnswer: "The digital revolution has created a paradigm where individuals can seamlessly shop, work, and socialize online, theoretically allowing them to live entirely without physical, face-to-face interaction. In my view, while this technological convenience offers certain practical benefits, the trend towards an entirely virtual existence is fundamentally a negative development due to its profound psychological and societal consequences.\n\nThe primary effect of this trend on the individual is an alarming increase in social isolation and mental health issues. Human beings are inherently social creatures who thrive on physical proximity, nuanced body language, and spontaneous physical interactions. When communication is reduced to text messages, video calls, and social media interactions, it loses its depth and authenticity. Consequently, individuals who rely solely on digital contact often report intense feelings of loneliness, alienation, and depression. Furthermore, a sedentary lifestyle dictated by remote work and online shopping inevitably leads to physical health deterioration, contributing to the global obesity epidemic.\n\nOn a societal level, the erosion of face-to-face contact severely damages community cohesion. Traditionally, public spaces such as local shops, offices, and community centers served as vital hubs where people from diverse backgrounds interacted, fostering mutual understanding and social trust. As these interactions move into isolated, curated digital echo chambers, society becomes increasingly fragmented and polarized. Without the empathy generated by real-world encounters, people are more prone to misunderstanding and conflict. Additionally, local economies suffer greatly; when everyone shops on global digital platforms, small local businesses fail, leading to the decline of vibrant community high streets.\n\nIn conclusion, while the ability to manage life entirely via the internet offers undeniable logistical convenience, it is a negative overall development. The devastating effects of isolation on individual mental health and the gradual destruction of community cohesion far outweigh the benefits of virtual efficiency. Society must actively strive to maintain a balance, utilizing technology as a tool rather than a replacement for genuine human connection."
    },
    { id: "dq4", type: "double", promptText: "Many museums and historical sites are mainly visited by tourists but not local people. Why is this the case? What can be done to attract more local people to visit these places?" },
    { id: "dq5", type: "double", promptText: "Success in life depends on hard work and determination, not on money or appearance. Do you agree or disagree? What other factors contribute to a successful life?" },
    { id: "dq6", type: "double", promptText: "People nowadays tend to have ready-made food rather than cooking for themselves. Why is this? Is this a positive or a negative development?" }
];
