const fs = require('fs');

// Missing Task 1 Answers
const missingT1 = {
    'l6': "Introduction:\nThe line graph illustrates the global temperature anomalies, measured in degrees Celsius (°C), over a forty-year period from 1980 to 2020.\n\nOverview:\nOverall, it is immediately apparent that global temperatures have experienced a continuous and significant upward trend over the four decades. The most rapid period of warming occurred in the latter half of the given timeframe.\n\nBody Paragraph 1:\nLooking at the first two decades, the temperature anomaly started at 0.25°C in 1980. This figure rose steadily, reaching 0.40°C by 1990. The rate of increase then slowed slightly over the next ten years, with the anomaly edging up by only 0.05°C to reach 0.45°C in the year 2000.\n\nBody Paragraph 2:\nHowever, the trend accelerated markedly from 2000 onwards. The anomaly surged to 0.70°C by 2010, which was the largest decade-on-decade increase up to that point. This rapid warming continued unabated over the final decade, with the temperature anomaly skyrocketing to a peak of 1.05°C by 2020, representing a total increase of 0.8°C since 1980.",
    'p4': "Introduction:\nThe pie chart provides a breakdown of the various transportation methods utilized by commuters to reach their workplaces in a particular city during the year 2023.\n\nOverview:\nOverall, it is clear that driving a private car was overwhelmingly the most popular mode of transport. Public transportation also played a significant role, while active methods such as walking and cycling were the least favored options.\n\nBody Paragraph 1:\nFocusing on motorized transport, private cars dominated the daily commute, accounting for exactly half (50%) of all journeys to work. Public transport was the second most common choice, making up a combined 30% of the total. Within this category, taking the bus was more popular than taking the train, representing 18% and 12% of commuters, respectively.\n\nBody Paragraph 2:\nIn contrast, non-motorized and active methods of transport were far less common. Cycling was chosen by 12% of commuters, making it exactly as popular as taking the train. Finally, walking was the least utilized mode of transport overall, with only 8% of the city's workforce choosing to commute on foot.",
    'p5': "Introduction:\nThe pie chart illustrates the primary reasons cited by employees for leaving their jobs, based on a survey conducted in 2021.\n\nOverview:\nOverall, financial dissatisfaction was the most significant factor driving employee turnover. Lack of career progression and poor management also contributed notably, while long commutes were the least common reason for resigning.\n\nBody Paragraph 1:\nLooking at the most prominent reasons, inadequate salary was the dominant factor, cited by more than a third (35%) of the surveyed employees. The desire for better career opportunities was the second most common motivation, accounting for 25% of resignations. Together, these two career and finance-related factors were responsible for 60% of all staff turnover.\n\nBody Paragraph 2:\nRegarding workplace environment and logistics, poor management was a significant issue, pushing 20% of employees to leave their positions. A poor work-life balance was cited by 15% of respondents. Finally, a long commute was the least pressing concern, driving only 5% of employees to resign from their jobs.",
    't3': "Introduction:\nThe table compares the nutritional profile—specifically calories, protein, fat, and carbohydrates—of 100-gram portions of four popular fast-food items: hamburgers, pizza, fried chicken, and French fries.\n\nOverview:\nOverall, fried chicken is the most calorie-dense and fat-rich option, while French fries contain the highest amount of carbohydrates. Conversely, hamburgers offer the most balanced nutritional profile, being the lowest in calories and relatively high in protein.\n\nBody Paragraph 1:\nIn terms of caloric content and fat, fried chicken tops the list with 320 kcal and 20g of fat per 100g serving. French fries are closely behind with 310 kcal, though they contain less fat at 15g. Pizza and hamburgers are comparatively lower in calories, providing 280 kcal and 250 kcal respectively, and contain 12g and 14g of fat.\n\nBody Paragraph 2:\nLooking at carbohydrates and protein, French fries are overwhelmingly carbohydrate-heavy, containing 40g, which is significantly more than pizza (33g). Hamburgers and fried chicken contain much fewer carbs at 20g and 15g. However, fried chicken and hamburgers provide the most protein (14g and 12g respectively), whereas French fries offer a mere 3g of protein, making them the least protein-rich food on the list.",
    't4': "Introduction:\nThe table presents the results of a consumer survey detailing satisfaction levels regarding the quality of goods, customer service, and value for money across three different supermarket chains (Chain A, Chain B, and Chain C).\n\nOverview:\nOverall, Chain C achieved the highest ratings for both quality and customer service, while Chain B excelled exclusively in value for money. Chain A generally received moderate ratings across all three categories.\n\nBody Paragraph 1:\nFocusing on product quality and service, Chain C was clearly the most highly regarded. It scored an impressive 92% for the quality of its goods and 85% for its customer service. Chain A followed, with respectable ratings of 85% for quality and 78% for service. In contrast, Chain B was the least favored in these areas, scoring only 72% for quality and 65% for customer service.\n\nBody Paragraph 2:\nHowever, when considering value for money, the trend was entirely reversed. Chain B was the undisputed leader in this category, with a massive 88% satisfaction rating. Chain A followed in second place with 65%. Meanwhile, despite its high quality and excellent service, Chain C was considered the worst value for money, satisfying only 55% of consumers in this regard.",
    'pr3': "Introduction:\nThe diagram illustrates the various stages involved in the process of recycling plastic bottles.\n\nOverview:\nOverall, the recycling process is a cyclical procedure consisting of nine main steps, beginning with the consumer disposing of the bottle and culminating in the creation of new end products.\n\nBody Paragraph 1:\nInitially, the process begins when consumers throw their used plastic bottles into designated recycling bins. These bins are subsequently emptied by garbage collection trucks, which transport the waste to a recycling center. Upon arrival, the collected bottles undergo a rigorous sorting process where workers manually separate them based on their material and color, removing any non-recyclable items.\n\nBody Paragraph 2:\nFollowing the sorting stage, the plastic bottles are heavily compressed into large blocks to save space. These blocks are then fed into a crushing machine, which grinds the plastic into small flakes. These flakes are thoroughly washed in water to remove impurities and labels. Once cleaned, the flakes are fed through a machine that heats and melts them, extruding the molten plastic to form small pellets. Finally, these plastic pellets are used as raw material to manufacture a variety of new products, such as clothing, pens, or new bottles.",
    'pr4': "Introduction:\nThe flow chart provides a step-by-step breakdown of the recruitment process typically utilized by a modern company.\n\nOverview:\nOverall, the hiring procedure is a sequential, multi-stage process involving nine distinct steps. It begins with the identification of a staffing need and concludes with the formal onboarding of the successful candidate.\n\nBody Paragraph 1:\nThe process commences when a department identifies a vacancy and subsequently writes a detailed job description. This description is then used to advertise the position on various platforms, such as the company website and job boards. Following the advertisement, the company receives and collects applications and resumes from interested candidates. The Human Resources department then screens these applications, shortlisting the most suitable individuals based on their qualifications.\n\nBody Paragraph 2:\nThe shortlisted candidates are subsequently invited to attend a primary interview. Based on the performance in this initial round, a smaller group is selected for a second, more rigorous interview or a practical skills test. After evaluating the final candidates, the hiring committee selects the best applicant and extends a formal job offer. If the candidate accepts the offer, the final stage is the onboarding process, where the new employee is officially integrated into the company.",
    'm3': "Introduction:\nThe two maps illustrate the extensive redevelopment that took place in a town center between the years 2010 and 2020.\n\nOverview:\nOverall, the town center was transformed from a vehicle-oriented commercial area into a more pedestrian-friendly and leisure-focused zone, highlighted by the complete removal of road traffic and the addition of dining facilities.\n\nBody Paragraph 1:\nIn 2010, the layout of the town center was relatively simple. A main street, which permitted cars, ran horizontally across the area. Situated directly below this road were two commercial buildings of equal size: a Post Office on the left and a Supermarket on the right.\n\nBody Paragraph 2:\nBy 2020, significant alterations had been made. The most notable change was the conversion of the main street into a designated Pedestrian Zone, completely banning vehicular traffic. Furthermore, the buildings underwent major changes. The Post Office was entirely demolished and replaced by a Cafe and Restaurants, reflecting a shift towards leisure. Meanwhile, the Supermarket on the right was significantly expanded, taking up more space than it did a decade earlier.",
    'mx2': "Introduction:\nThe pie chart illustrates the primary causes of land degradation globally, while the table details how these causes affected three distinct regions (North America, Europe, and Oceania) during the 1990s.\n\nOverview:\nOverall, over-grazing was the leading global cause of land degradation. Regionally, Europe suffered the highest total percentage of degraded land, primarily due to deforestation, whereas North America experienced the least degradation.\n\nBody Paragraph 1:\nAccording to the pie chart, over-grazing was responsible for the largest share of global land degradation at 35%. Deforestation was the second most significant factor (30%), closely followed by over-cultivation (28%). Other minor causes accounted for the remaining 7%.\n\nBody Paragraph 2:\nThe table reveals distinct regional variations. Europe had the highest proportion of degraded land at 23%, with deforestation being the main culprit, responsible for 9.8% of this damage. Oceania (Australia and New Zealand) had the second-highest total degradation at 13%. Unlike Europe, Oceania's land was overwhelmingly damaged by over-grazing (11.3%), while over-cultivation had absolutely zero impact in this region. Finally, North America had the lowest overall land degradation at just 5%, with over-cultivation (3.3%) being the most prominent cause, while deforestation and over-grazing played minimal roles."
};

const missingT2 = {
    'd6': "Introduction:\nThe debate surrounding healthcare funding is highly contentious. While some argue that medical care should be completely free and fully funded by the government, others believe that individuals should bear the responsibility for their own healthcare costs through private insurance or out-of-pocket payments.\n\nBody Paragraph 1:\nProponents of free, government-funded healthcare argue that access to medical treatment is a fundamental human right, not a privilege reserved for the wealthy. When healthcare is heavily subsidized by taxes, it ensures that all citizens, regardless of their socioeconomic status, can receive necessary treatments. This approach prevents situations where individuals go bankrupt due to unforeseen medical emergencies or avoid seeking early treatment because of prohibitive costs. Furthermore, a healthy population is essential for a productive workforce and a thriving economy, making public healthcare a sound national investment.\n\nBody Paragraph 2:\nConversely, opponents argue that a completely free healthcare system is economically unsustainable and prone to inefficiency. Government-funded systems often suffer from long waiting times, bureaucratic delays, and a lack of cutting-edge technology due to budget constraints. Those who advocate for private healthcare maintain that market competition drives hospitals and clinics to provide higher quality care and more efficient services. Additionally, they argue that forcing taxpayers to fund the lifestyle-related illnesses of others is inherently unfair, and that individuals should take financial responsibility for their own health.\n\nConclusion:\nIn conclusion, while private healthcare systems may offer greater efficiency and faster access for those who can afford it, I believe that healthcare is a basic human necessity. Therefore, governments should strive to provide a robust, free public healthcare system, perhaps supplemented by optional private insurance, to ensure that no citizen is denied medical care due to financial hardship.",
    'ps4': "Introduction:\nIn recent decades, childhood obesity has surged to alarming levels in many developed nations. This essay will examine the primary causes of this growing epidemic and propose viable solutions to address it.\n\nBody Paragraph 1:\nThe principal cause of childhood obesity is a drastic shift in lifestyle and dietary habits. Modern children consume significantly more processed foods, fast food, and sugary beverages, which are high in empty calories and low in nutritional value, than previous generations. This poor diet is exacerbated by a severe decline in physical activity. The proliferation of smartphones, video games, and on-demand television has led to a highly sedentary lifestyle. Instead of playing outdoors, many children now spend hours indoors engaged in screen-based entertainment, burning very few calories in the process.\n\nBody Paragraph 2:\nTo combat this issue, a multi-faceted approach involving parents, schools, and the government is required. Firstly, parents must take responsibility by providing nutritious, home-cooked meals and strictly limiting screen time, encouraging their children to engage in outdoor sports. Secondly, schools should mandate daily physical education classes and ensure that cafeterias serve healthy, balanced meals, completely removing vending machines that dispense junk food. Finally, governments can intervene by imposing heavy taxes on sugary products and heavily regulating junk food advertising aimed at minors.\n\nConclusion:\nIn conclusion, the epidemic of childhood obesity is primarily driven by poor diets and sedentary, screen-centric lifestyles. However, by implementing stricter dietary guidelines in schools, encouraging physical activity at home, and enacting government regulations on unhealthy foods, this concerning trend can be successfully reversed.",
    'ps5': "Introduction:\nIn many cities around the world, traffic congestion has become a severe and escalating problem, leading to increased pollution, wasted time, and economic inefficiency. This essay will outline the main causes of this issue and suggest effective measures to alleviate it.\n\nBody Paragraph 1:\nThe primary cause of urban traffic congestion is the exponential increase in private vehicle ownership. As populations grow and urban sprawl pushes residential areas further from city centers, relying on a private car has become a necessity for many commuters. This reliance is heavily compounded by inadequate public transportation infrastructure. In many cities, bus and train networks are unreliable, overcrowded, or fail to connect key suburban areas to commercial hubs. Consequently, people prefer the comfort and reliability of their own vehicles, leading to millions of cars overwhelming road networks designed for much smaller capacities.\n\nBody Paragraph 2:\nTo solve this pressing issue, governments must prioritize heavy investment in public transportation. Developing extensive, affordable, and highly efficient subway and bus networks would provide a viable alternative to driving, thereby reducing the number of cars on the road. Additionally, city planners could implement congestion charging zones, similar to those in London or Singapore, where drivers must pay a substantial fee to enter the city center during peak hours. This financial deterrent strongly encourages carpooling or the use of public transit.\n\nConclusion:\nIn conclusion, traffic congestion is largely the result of over-reliance on private cars and inadequate public transit. However, by significantly upgrading public transportation infrastructure and implementing congestion pricing, cities can effectively reduce traffic volume and improve urban mobility.",
    'ps6': "Introduction:\nIn modern society, many individuals experience high levels of stress, which can lead to severe mental and physical health issues. This essay will discuss the primary causes of modern stress and propose effective solutions to help individuals manage it.\n\nBody Paragraph 1:\nThe leading cause of contemporary stress is the demanding nature of modern work environments. In a highly competitive global economy, employees often face long working hours, immense pressure to meet tight deadlines, and the constant fear of job insecurity. This is exacerbated by the advent of digital technology and smartphones, which blur the boundaries between professional and personal life. Because people are constantly connected via emails and messaging apps, they find it incredibly difficult to 'switch off' from work, leading to chronic exhaustion and burnout.\n\nBody Paragraph 2:\nTo address this issue, both individuals and employers must take proactive steps. Individuals must establish firm boundaries by refusing to check work emails during evenings and weekends, dedicating time instead to relaxation, exercise, and hobbies. Employers, on the other hand, have a crucial responsibility to foster a healthy work-life balance. They can achieve this by implementing flexible working hours, mandating regular breaks, and strictly prohibiting managers from contacting staff outside of official working hours. Furthermore, companies should offer mental health support programs to help employees cope with workplace pressures.\n\nConclusion:\nIn conclusion, the primary drivers of modern stress are intense professional demands and a lack of separation between work and home life. However, by establishing strict personal boundaries and implementing supportive corporate policies, this modern epidemic can be effectively managed and reduced.",
    'a4': "Introduction:\nWhile technological advancements have undeniably accelerated the pace of modern life, there is an ongoing debate about whether this has actually led to more free time. I strongly agree that despite the invention of time-saving devices, modern individuals generally have less leisure time than in the past.\n\nBody Paragraph 1:\nFirstly, the modern working environment is characterized by intense competition and ever-increasing productivity demands. Although technology like computers and software have made tasks faster, employers simply expect more work to be completed within the same timeframe. Furthermore, smartphones and the internet mean that employees are perpetually accessible. The expectation to reply to emails and messages outside of official working hours effectively extends the workday into the evening and weekends, drastically reducing the amount of true, uninterrupted leisure time.\n\nBody Paragraph 2:\nSecondly, the nature of modern consumer culture demands higher incomes, forcing people to work longer hours to maintain their lifestyle. In the past, a single income was often sufficient to support a family, allowing the other partner significant time for domestic duties and leisure. Today, the high cost of living usually requires both partners to work full-time. Even time-saving domestic appliances, such as washing machines and dishwashers, merely free up time that is immediately reallocated to commuting or working overtime, rather than genuine relaxation.\n\nConclusion:\nIn conclusion, while technology has automated many manual tasks, it has simultaneously increased professional expectations and eroded the boundary between work and home. Therefore, I firmly agree that modern life has paradoxically resulted in a significant reduction in genuine free time.",
    'a5': "Introduction:\nThe issue of climate change is arguably the most pressing challenge facing humanity today. While some argue that it is the sole responsibility of multinational corporations to solve this crisis, I completely disagree with this notion, as it requires a collaborative effort from individuals, governments, and businesses alike.\n\nBody Paragraph 1:\nIt is undeniably true that large corporations contribute massively to global emissions, particularly those in the fossil fuel, manufacturing, and transportation sectors. However, to place the burden of solving climate change solely on them ignores the critical role of government legislation. Corporations operate primarily to maximize profit; they are unlikely to adopt expensive, green technologies voluntarily. Therefore, it is the responsibility of governments to enforce strict environmental regulations, implement carbon taxes, and subsidize renewable energy initiatives. Without strong governmental policy, corporate action will remain slow and insufficient.\n\nBody Paragraph 2:\nFurthermore, individual consumers hold immense power and responsibility in combating climate change. Corporate production is ultimately driven by consumer demand. If individuals collectively choose to reduce their meat consumption, utilize public transport, and purchase sustainably sourced products, businesses will be forced to adapt their practices to survive in the market. Individual actions, such as minimizing household waste and conserving electricity, aggregate into massive environmental impacts, proving that everyday citizens are a crucial part of the solution.\n\nConclusion:\nIn conclusion, while large companies are major polluters, solving climate change cannot be their responsibility alone. I firmly believe that this global crisis can only be resolved through a combination of strict government regulations, sustainable corporate practices, and conscientious individual choices.",
    'a6': "Introduction:\nThere is a growing debate regarding the primary purpose of a university education. While some argue that universities should exclusively teach practical skills to prepare students for the workforce, I disagree with this narrow view, believing that higher education should offer a broader, holistic development.\n\nBody Paragraph 1:\nThose who support a purely vocational approach argue that the main goal of university is to secure employment. They believe that teaching abstract theory is a waste of time and that students should graduate with highly specific, technical skills required by modern industries. While vocational training is undeniably important, particularly in fields like engineering or medicine, designing all university courses solely around current job market demands is short-sighted. The modern economy evolves rapidly, and highly specific technical skills can become obsolete within a few years due to technological advancements.\n\nBody Paragraph 2:\nConversely, a broader academic education equips students with versatile, lifelong skills. Subjects like philosophy, history, and literature develop critical thinking, complex problem-solving, and advanced communication skills. These \"soft skills\" are highly valued by employers because they enable graduates to adapt to new situations, think creatively, and lead teams effectively. Furthermore, university is not just a training factory; it is a place for intellectual growth, personal development, and the pursuit of knowledge for its own sake, which helps create well-rounded, informed citizens.\n\nConclusion:\nIn conclusion, while equipping students for the workplace is an important function of universities, it should not be their sole purpose. I firmly believe that higher education must balance practical skills with broad academic knowledge to develop adaptable, critical thinkers prepared for a changing world.",
    'dq4': "Introduction:\nToday, the ability to travel quickly across the globe has transformed international tourism and business. While the ease of modern travel brings undeniable economic and cultural benefits, it also presents significant environmental and social challenges. \n\nBody Paragraph 1:\nOne of the main advantages of fast global travel is the massive boost it provides to international economies. Tourism is a primary source of income for many developing nations, creating millions of jobs in the hospitality, aviation, and service sectors. Furthermore, rapid air travel facilitates international trade and business operations, allowing multinational companies to function smoothly across different continents. Culturally, easy travel promotes global understanding and tolerance, as people have the opportunity to experience different ways of life firsthand, breaking down stereotypes and fostering international cooperation.\n\nBody Paragraph 2:\nHowever, these benefits are accompanied by severe disadvantages, most notably environmental degradation. The aviation industry is a major contributor to greenhouse gas emissions, and the sheer volume of global flights significantly accelerates climate change. Additionally, the influx of tourists can lead to 'overtourism', which puts immense strain on local infrastructure, degrades natural habitats, and often drives up the cost of living for local residents. Furthermore, the ease of global travel facilitates the rapid spread of infectious diseases, as seen in recent global pandemics.\n\nConclusion:\nIn conclusion, the ability to travel quickly and easily around the world offers immense economic and cultural advantages. Nevertheless, the environmental damage and strain on local communities represent significant drawbacks. Therefore, while global travel is beneficial, it must be managed sustainably to mitigate its negative impacts.",
    'dq5': "Introduction:\nIn recent years, many nations have increasingly turned to nuclear power as a primary method of electricity generation. While this technology offers a highly efficient and low-carbon energy solution, it also carries profound risks that must be carefully considered.\n\nBody Paragraph 1:\nThe most significant advantage of nuclear power is its ability to generate massive amounts of electricity with a remarkably low carbon footprint. Unlike fossil fuels such as coal and natural gas, nuclear reactors do not emit greenhouse gases during operation, making them a crucial tool in the fight against climate change. Furthermore, nuclear energy is highly reliable and provides a stable 'baseload' of power, unlike renewable sources like wind and solar, which are dependent on fluctuating weather conditions. A single nuclear plant can power millions of homes continuously for years with very little fuel.\n\nBody Paragraph 2:\nDespite these benefits, the disadvantages of nuclear energy are substantial and potentially catastrophic. The most prominent concern is the risk of a nuclear meltdown, as witnessed in Chernobyl and Fukushima. Such disasters release devastating amounts of radiation, rendering huge areas of land uninhabitable and causing severe, long-term health consequences for the population. Additionally, nuclear reactors produce highly toxic radioactive waste that remains hazardous for thousands of years. Currently, there is no permanent, completely safe method for disposing of this waste, creating a dangerous legacy for future generations.\n\nConclusion:\nIn conclusion, nuclear power provides a reliable and environmentally clean source of massive energy. However, the catastrophic consequences of potential accidents and the unresolved issue of radioactive waste disposal represent severe disadvantages. Thus, its use must be approached with extreme caution and stringent safety regulations.",
    'dq6': "Introduction:\nThe prevalence of remote work has increased dramatically, fundamentally altering the traditional employment landscape. While working from home offers significant flexibility and cost savings, it also presents challenges regarding isolation and team cohesion.\n\nBody Paragraph 1:\nThe primary advantage of telecommuting is the substantial improvement in work-life balance it offers employees. By eliminating the daily commute, workers save hours of time each week, which can be redirected towards family, exercise, or personal hobbies. This reduction in travel also decreases traffic congestion and significantly lowers carbon emissions, benefiting the environment. For employers, allowing staff to work remotely can lead to massive reductions in overhead costs, as companies require less physical office space and can save on utilities and supplies.\n\nBody Paragraph 2:\nHowever, the shift towards remote work is not without its drawbacks. The most prominent disadvantage is the sense of social isolation and disconnection that many employees experience. The absence of face-to-face interactions, casual office conversations, and physical meetings can make it difficult to build strong team dynamics and corporate culture. Furthermore, working from home can blur the boundaries between professional and personal life, leading some employees to overwork and experience burnout. Additionally, managers may find it more challenging to monitor productivity and provide immediate mentorship or feedback.\n\nConclusion:\nIn conclusion, working from home provides exceptional benefits in terms of flexibility, environmental impact, and cost reduction. Nevertheless, the potential for social isolation and the blurring of work-life boundaries are significant disadvantages. Ultimately, a hybrid model combining both office and remote work may offer the most balanced approach."
};

// Function to format answers to explicitly have Introduction, Body, Conclusion labels
function upgradeAnswer(text, type) {
    if (text.includes('Introduction:')) return text; // already formatted
    const parts = text.split('\\n\\n').map(p => p.trim());
    if (parts.length < 3) return text; 

    if (type === 'task1') {
        parts[0] = "Introduction:\\n" + parts[0];
        parts[1] = "Overview:\\n" + parts[1];
        for (let i = 2; i < parts.length; i++) {
            parts[i] = "Body Paragraph " + (i - 1) + ":\\n" + parts[i];
        }
    } else {
        parts[0] = "Introduction:\\n" + parts[0];
        for (let i = 1; i < parts.length - 1; i++) {
            parts[i] = "Body Paragraph " + i + ":\\n" + parts[i];
        }
        parts[parts.length - 1] = "Conclusion:\\n" + parts[parts.length - 1];
    }
    return parts.join('\\n\\n');
}

function processFile(filePath, missingDict, type) {
    let content = fs.readFileSync(filePath, 'utf8');
    
    // Add missing answers
    for (const [id, answer] of Object.entries(missingDict)) {
        const regex = new RegExp('(id:\\s*["\']' + id + '["\'],[\\s\\S]*?)(chartConfig|htmlContent)');
        content = content.replace(regex, (match, p1, p2) => {
            return p1 + 'modelAnswer: ' + JSON.stringify(answer) + ',\\n        ' + p2;
        });
    }

    // Now, regex replace all modelAnswer strings to upgrade them
    content = content.replace(/modelAnswer:\s*"(.*?)"/g, (match, p1) => {
        // Unescape the string slightly to manipulate it
        let text = p1.replace(/\\\\n/g, '\n');
        text = upgradeAnswer(text, type);
        // Escape back
        text = text.replace(/\n/g, '\\\\n');
        return 'modelAnswer: "' + text + '"';
    });

    fs.writeFileSync(filePath, content);
}

processFile('d:/Projects/Websites/@Tests/ieltswriting/questions.js', missingT1, 'task1');
processFile('d:/Projects/Websites/@Tests/ieltswriting/questions2.js', missingT2, 'task2');
